# EDA: Slovo

In [3]:
annotations_path = 'C:/Users/pdkud/Documents/Learning/Магистратура МФТИ/slovo/slovo_annotations/SLOVO_DATAFRAME.tsv'

In [1]:
import os
import pandas as pd

In [4]:
slovo_df = pd.read_csv(annotations_path, sep='\t')

In [5]:
slovo_df.head()

,attachment_id,text,user_id,height,width,length,begin,end
0,44e8d2a0-7e01-450b-90b0-beb7400d2c1e,Ё,185bd3a81d9d618518d10abebf0d17a8,640,360,156.0,36,112
1,df5b08f0-41d1-4572-889c-8b893e71069b,А,185bd3a81d9d618518d10abebf0d17a8,640,360,150.0,36,76
2,17f53df4-c467-4aff-9f48-20687b63d49a,Р,185bd3a81d9d618518d10abebf0d17a8,640,360,133.0,40,97
3,e3add916-c708-4339-ad98-7e2740be29e9,Е,185bd3a81d9d618518d10abebf0d17a8,640,360,144.0,43,107
4,bd7272ed-1850-48f1-a2a8-c8fed523dc37,Ч,185bd3a81d9d618518d10abebf0d17a8,640,360,96.0,20,70

In [17]:
slovo_df['frames_cnt'] = slovo_df['end']-slovo_df['begin']+1
slovo_df.head()

,attachment_id,text,user_id,height,width,length,begin,end,frames_cnt
0,44e8d2a0-7e01-450b-90b0-beb7400d2c1e,Ё,185bd3a81d9d618518d10abebf0d17a8,640,360,156.0,36,112,77
1,df5b08f0-41d1-4572-889c-8b893e71069b,А,185bd3a81d9d618518d10abebf0d17a8,640,360,150.0,36,76,41
2,17f53df4-c467-4aff-9f48-20687b63d49a,Р,185bd3a81d9d618518d10abebf0d17a8,640,360,133.0,40,97,58
3,e3add916-c708-4339-ad98-7e2740be29e9,Е,185bd3a81d9d618518d10abebf0d17a8,640,360,144.0,43,107,65
4,bd7272ed-1850-48f1-a2a8-c8fed523dc37,Ч,185bd3a81d9d618518d10abebf0d17a8,640,360,96.0,20,70,51

In [18]:
slovo_df.groupby(['height', 'width']).agg({'attachment_id' : ['count'], 'frames_cnt':['sum']}).sort_values(['height', 'width'])

             attachment_id frames_cnt
                     count        sum
height width
358    490               1         45
       494               1         38
       498               1         29
       508               1         45
       514               1         28
       518               1         31
       522               1         35
       534               1         37
       552               1         37
       560               1         53
       580               1         41
       780               8        448
360    360             258      11956
       440               1         30
       480               1         64
       522               1        136
       528               1         46
       542               1         54
       550               1         39
       558               1         35
       560               2         99
       640            2436     135347
       720               5        275
       752               7        362
       786               2        147
404    358               1         37
420    358               1         40
424    360               1         47
426    358               1         42
436    358               1         68
548    360               1         38
576    360               4        298
622    358               5        229
636    360             117       6144
640    360           15023     756961
720    360             236      10460
752    360              23        822
772    360              32       1907
780    358             152       6549
786    360              52       2775
800    360              15        856
840    358            1599      74715

In [20]:
slovo_df.agg({'attachment_id' : ['count'], 'frames_cnt':['sum']})

       attachment_id  frames_cnt
count        20000.0         NaN
sum              NaN   1011445.0

In [22]:
len(slovo_df.text.unique())

1000

In [24]:
slovo_df['CLEANED'] = slovo_df.text.str.lower()\
    .str.replace("[.?!,:.\"–=#\^]", "", regex=True)

In [25]:
slovo_df['LENGTH'] = slovo_df['CLEANED'].str.split(' ').str.len()

In [26]:
# Уникальные фразы
len(set(slovo_df[slovo_df['LENGTH'] > 1.0].CLEANED))

68